services:
  - type: web
    name: bybit-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bybit_bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
